# Generated by Django 3.1.3 on 2020-11-15 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('gsis_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('season_type', models.CharField(max_length=50)),
                ('week', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=10)),
                ('avg_time_to_throw', models.FloatField()),
                ('avg_completed_air_yards', models.FloatField()),
                ('avg_intended_air_yards', models.FloatField()),
                ('avg_air_yards_differential', models.FloatField()),
                ('aggressiveness', models.FloatField()),
                ('max_completed_air_distance', models.FloatField()),
                ('avg_air_yards_to_sticks', models.FloatField()),
                ('attempts', models.IntegerField()),
                ('pass_yards', models.IntegerField()),
                ('pass_touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('passer_rating', models.FloatField()),
                ('completions', models.IntegerField()),
                ('completion_percentage', models.FloatField()),
                ('expected_completion_percentage', models.FloatField()),
                ('completion_percentage_above_expectation', models.FloatField()),
                ('avg_air_distance', models.FloatField()),
                ('max_air_distance', models.FloatField()),
                ('player_jersey_number', models.IntegerField()),
                ('gsis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_next_gen_stats.player', to_field='gsis_id')),
            ],
        ),
    ]
