# Generated by Django 3.1.3 on 2020-11-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_next_gen_stats', '0002_auto_20201114_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passingstats',
            name='aggressiveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='avg_air_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='avg_air_yards_differential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='avg_air_yards_to_sticks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='avg_completed_air_yards',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='avg_intended_air_yards',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='avg_time_to_throw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='completion_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='completion_percentage_above_expectation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='completions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='expected_completion_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='interceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='max_air_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='max_completed_air_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='pass_touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='pass_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='passer_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='player_jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
