# Generated by Django 3.1.3 on 2020-11-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_next_gen_stats', '0004_rushingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('season_type', models.CharField(max_length=50)),
                ('week', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=10)),
                ('player_jersey_number', models.IntegerField(blank=True, null=True)),
                ('avg_cushion', models.FloatField(blank=True, null=True)),
                ('avg_separation', models.FloatField(blank=True, null=True)),
                ('avg_intended_air_yards', models.FloatField(blank=True, null=True)),
                ('percent_share_of_intended_air_yards', models.FloatField(blank=True, null=True)),
                ('receptions', models.IntegerField(blank=True, null=True)),
                ('targets', models.IntegerField(blank=True, null=True)),
                ('catch_percentage', models.FloatField(blank=True, null=True)),
                ('yards', models.IntegerField(blank=True, null=True)),
                ('rec_touchdowns', models.IntegerField(blank=True, null=True)),
                ('avg_yac', models.FloatField(blank=True, null=True)),
                ('avg_expected_yac', models.FloatField(blank=True, null=True)),
                ('avg_yac_above_expectation', models.FloatField(blank=True, null=True)),
                ('gsis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_next_gen_stats.player', to_field='gsis_id')),
            ],
        ),
    ]
