# Generated by Django 3.1.3 on 2020-11-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_next_gen_stats', '0006_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
